### ISSUE TITLE
ncc is pretty awesome, maybe

### ISSUE THREAD

**Issue by ghost** [pfalcon/awesome-stuff#1]
You should record [ncc](https://github.com/gnuless/ncc) in here.

I've plugged you in the acknowledgements of that project, since you expressed interest in its previous incarnation some time ago.

**Comment by pfalcon** [comment]
Thanks for reviving the project! I've added it to wiki here, but this is just a random personal-notes repo about which I forgotten ;-). My idea was to post about it to Reddit's /r/Compilers, but I see you've done that already: https://github.com/gnuless/ncc . So, a star/upvote! ;-).

**Comment by ghost** [comment]
Thanks for nudging me in the right direction.

I guess we can close this issue now ;)

Take care ..
